theme: jekyll-theme-tactile
title: Welcome to my Digital Cultures Portfolio! 
description: Add this to your bookmarks to keep up with my work in Digital Cultures at Seattle University! Enjoy - Rachel 
